spring.application.name=system
# Oracle DB Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.web.resources.static-locations=file:uploads/
# ✅ الصحيح لـ MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ Hibernate Dialect الصحيح
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.transaction=DEBUG